name: frc
description: A Flutter camera plugin that detects faces
version: 0.0.1
homepage: https://github.com/msarifin29/frc

environment:
  sdk: ^3.5.1
  flutter: ">=3.3.0"

dependencies:
  camera: ^0.11.0+2
  flutter:
    sdk: flutter
  google_mlkit_face_detection: ^0.12.0
  image: ^4.5.0
  plugin_platform_interface: ^2.0.2
  tflite_flutter: ^0.11.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.js.frc
        pluginClass: FrcPlugin
      ios:
        pluginClass: FrcPlugin

  # assets:
  #   - assets/
